# -*- coding: utf-8 -*-
"""project-2diabteic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11yoW2yO-GqsBLM_AdtjziI9XUKoPK49V
"""



"""importing"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm

from sklearn.metrics  import accuracy_score

data=pd.read_csv('/content/diabetes (1).csv')

data.head()

data.describe()

data.shape

"""seperating features and target"""

x=data.drop(columns='Outcome',axis=1)
y=data['Outcome']

print(x)
print(y)

"""0>-- diabetic
1 ->> non diabeteic

Data Standardization
"""

scalar=StandardScaler()

standard_data=scalar.fit_transform(x)
print(standard_data)

x=standard_data

"""spliting into train and test data

"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y, random_state=2)

print(x_train.shape,x_test.shape)

classifier=svm.SVC(kernel='linear')

classifier.fit(x_train,y_train)

"""machine leraning model"""

#modelevaluation
x_train_pre=classifier.predict(x_train)
training_data=accuracy_score(x_train_pre,y_train)
print(training_data)

x_test_pre=classifier.predict(x_test)
test_data=accuracy_score(x_test_pre,y_test)
print(test_data)

"""making a predictive system

"""

input=(5,166,72,19,175,25.8,0.587,51)
input_numpy=np.asarray(input)
input_reshape=input_numpy.reshape(1,-1)
#standardize the input data
std_data=scalar.transform(input_reshape)
predit=classifier.predict(std_data)
print(predit)

if(predit[0]==0):
  print("Person is not diabetic")
else:
  print("person is diabteic")